const books = [
  'Fiction',
  'Non-Fiction',
  'Science',
  'Technology',
  'Engineering',
  'Mathematics',
  'History',
  'Biography',
  'Fantasy',
  'Adventure',
  'Mystery',
  'Thriller',
  'Romance',
  'Self-help',
  'Philosophy',
  'Psychology',
  'Poetry',
  'Drama',
  'Classics',
  'Science Fiction',
  'Horror',
  'Travel',
  'Children',
  'Young Adult',
  'Art',
  'Business',
  'Religion',
  'Politics',
  'Cookbooks',
  'Comics',
  'Graphic Novels',
  'Others',
];

module.exports = books;  // Correct export
